services:
  user-service:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./users/.env
    depends_on:
      mongodb:
          condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./users
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  client-service:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      mongodb:
          condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - client-service
      - user-service
    ports:
      - 80:80

  