name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Generate environment files for all services
      run: |
        cp ./users/.env.sample ./users/.env
        cp ./client/.env.sample ./client/.env

    - name: Build Docker Compose services
      run: docker compose up --build -d

    - name: Verify services are running
      run: docker compose ps

    - name: Shut down services
      run: docker compose down
